// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pmvalhzpdejoubdunupu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtdmFsaHpwZGVqb3ViZHVudXB1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyOTAwNzAsImV4cCI6MjA2Mzg2NjA3MH0.E4wYd-T0juwOcCofrUmrTKieIYR_5Y8Vs8Ud02YCZfs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);